name = "FinEtoolsMultimaterialVibEP"
uuid = "924b30c9-72fd-43b6-97c0-022972fd2000"
authors = ["Petr Krysl <pkrysl@ucsd.edu>"]
version = "0.1.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FinEtools = "91bb5406-6c9a-523d-811d-0644c4229550"
FinEtoolsAcoustics = "72171760-8bdd-11e9-0dbf-b3b512e82515"
FinEtoolsDeforLinear = "e9187c00-8bdd-11e9-1e70-7ba8303116a2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Arpack =  "^0.5"
DataAPI =  "^1.9"
DataStructures =  "^0.18"
FinEtools =  "^5.3"
FinEtoolsAcoustics =  "^1.1"
FinEtoolsDeforLinear =  "^1.2"
FinEtoolsMultimaterialVibEP =  "^0.1"
Gnuplot =  "^1.4"
Infiltrator =  "^1.1"
JSON =  "^0.21"
MAT =  "^0.10"
Missings =  "^1.0"
OrderedCollections =  "^1.4"
PlotlyJS =  "^0.18"
Revise =  "^3.3"
SortingAlgorithms =  "^1.0"
StatsBase =  "^0.33"
UnicodePlots = "^2.7"